backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Zum Testen vom netlify-cms:
# local_backend: true
# npx netlify-cms-proxy-server

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/media" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Artikel" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titelintro (nur was kurzes)", name: "titleintro", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kurzbeschreibung (ca. 200 Zeichen)", name: "description", widget: "text" }
      - { label: "Autor", name: "authorname", widget: "string", default: "Hartmuth Sandtner"}
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: 'Kategorie', name: 'category', required: true, widget: 'select', options: ['Panorama', 'Kultur', 'Politik', 'Meinung'] }
      - { label: "Themen (durch Komma trennen)", name: "tags", widget: "list" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
